name: TownyDiscord
version: '1.0'
main: net.worldmc.townyDiscord.TownyDiscord
api-version: '1.21'
authors: [Ezekiel Pari]
dependencies:
  server:
    Towny:
      load: BEFORE
    DiscordSRV:
      load: BEFORE